name: Maven Serenity TestNG Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      # Setup JDK
  
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
           java-version: '8'
           distribution: 'temurin'
           cache: maven
      
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Run the tests with Maven (including ExtentReports)
      - name: Run tests with Maven
        run: mvn test

      # Upload the Serenity and ExtentReports as artifacts
      - name: Upload Extent Reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            Reporte/Tests_Report_Fakestoreapi_Products.html # Subir el reporte HTML de ExtentReports

      # Publish ExtentReports URL to the workflow's output
      - name: Publish ExtentReports URL
        run: |
          if [ -f "Reporte/Tests_Report_Fakestoreapi_Products.html" ]; then
            echo "ExtentReports are available at: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/artifacts"
          else
            echo "No ExtentReports found"
          fi
