name: Maven Serenity TestNG Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
  
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
           java-version: '8'
           distribution: 'temurin'
           cache: maven
      
      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run tests with Maven
        run: mvn test

      - name: Upload Extent Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: Reporte/Tests_Report_Fakestoreapi_Products.html

